AK-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ak bills"
  enabled: true
  environment: scrapers
  triggers:
#    - cron: 0 */6 * * ?
    - cron: 0 8 * * ?
  timeout_minutes: 360
  next_tasks:
    - AK-text

AK-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ak"
  enabled: true
  environment: scrapers
