AL-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update al bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 5 * * ?
  timeout_minutes: 360
  next_tasks:
    - AL-text

AL-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update al"
  enabled: true
  environment: scrapers
