AR-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ar bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 6 * * ?
  timeout_minutes: 360
  next_tasks:
    - AR-text

AR-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update ar"
  enabled: true
  environment: scrapers
