AZ-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update az bills"
  enabled: true
  environment: scrapers
  triggers:
#    - cron: 23 */2 * * ?
    - cron: 30 7 * * ?
  timeout_minutes: 720
  next_tasks:
    - AZ-text

AZ-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update az"
  enabled: true
  environment: scrapers

AZ-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update az events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 12 0 * * ?
  timeout_minutes: 60
