CA-scrape:
  image: openstates/openstates:california
  entrypoint: [sh, -c, 'sed -i "s/user                    = mysql/user                    = root/" /etc/mysql/mariadb.conf.d/50-server.cnf && mysql_install_db --user=root && mkdir /run/mysqld && mysqld --user root --max_allowed_packet=512M & /opt/openstates/openstates/scrapers/ca/download.sh && poetry run os-update ca bills']
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 0,12 * * ?
  memory: 4096
  cpu: 512
  timeout_minutes: 360
  next_tasks:
    - CA-text

CA-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update ca"
  enabled: true
  environment: scrapers
