CA-scrape:
  image: openstates/scrapers-california
  entrypoint: "/ca-entrypoint.sh bills"
  enabled: false
  environment: scrapers
  triggers:
    - cron: 0 0,12 * * ?
  memory: 4096
  cpu: 512
  timeout_minutes: 360
  next_tasks:
    - CA-text

CA-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ca"
  enabled: false
  environment: scrapers

CA-events:
  image: openstates/scrapers-california
  entrypoint: "poetry run os-update ca events_web"
  enabled: false
  environment: scrapers
  triggers:
    - cron: 30 */6 * * ?
  memory: 4096
  cpu: 512
  timeout_minutes: 60
