name: CA
entrypoint: [sh, -c, "mysql_install_db --user=root && mkdir /run/mysqld && mysqld --user root --datadir=/opt/openstates/openstates/data --max_allowed_packet=512M & /opt/openstates/openstates/openstates/ca/download.sh && ./pupa-scrape.sh ca bills"]
cpu: 512
memory_soft: 128
memory: 4096
cron: 1 */12 * * ? *
environment: openstates
paramstore: scrapers
image: openstates/openstates
enabled: true
