CO-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update co bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - CO-text

CO-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update co"
  enabled: true
  environment: scrapers
