CO-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update co bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 7 * * ?
  next_tasks:
    - CO-text

CO-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update co"
  enabled: true
  environment: scrapers
