CT-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ct bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 5 * * ?
  timeout_minutes: 360
  next_tasks:
    - CT-text

CT-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update ct"
  enabled: true
  environment: scrapers
