DC-scrape:
  image: openstates/openstates
  entrypoint: "poetry run pupa update dc bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 5 * * ?
  next_tasks:
    - DC-text

DC-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update dc"
  enabled: true
  environment: scrapers
