DE-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update de bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */2 * * ?
#    - cron: 0 5 * * ?
  memory: 1024
  timeout_minutes: 2160 # regularly 12 hours, 36 hours to be safe :(
  next_tasks:
    - DE-text

DE-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update de"
  enabled: true
  environment: scrapers
