DE-scrape:
  image: openstates/openstates
  entrypoint: "poetry run pupa update de bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 5 * * ?
  memory: 1024
  next_tasks:
    - DE-text

DE-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update de"
  enabled: true
  environment: scrapers
