FL-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update fl bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 720
  next_tasks:
    - FL-text

FL-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update fl --clear-errors"
  enabled: true
  environment: scrapers
