GA-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ga bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 480
  next_tasks:
    - GA-text

GA-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ga"
  enabled: true
  environment: scrapers
