HI-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update hi bills scrape_--realtime"
  enabled: true
  environment: scrapers
  triggers:
    # runs once a week at midnight on sunday morning
    - cron: 0 0 * * 0
  timeout_minutes: 2880  # 48 hours :(
  next_tasks:
    - HI-text

HI-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update hi"
  enabled: true
  environment: scrapers
