HI-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update hi bills"
  enabled: true
  environment: scrapers
  triggers:
#    - cron: 0 */6 * * ?
    - cron: 0 9 * * ?
  timeout_minutes: 360
  next_tasks:
    - HI-text

HI-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update hi"
  enabled: true
  environment: scrapers

HI-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update hi events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 30 5 * * ?
  timeout_minutes: 60
