HI-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update hi bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 9 * * ?
  next_tasks:
    - HI-text

HI-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update hi"
  enabled: true
  environment: scrapers
