ID-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update id bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - ID-text

ID-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update id"
  enabled: true
  environment: scrapers
