ID-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update id bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 15 */2 * * ?
#    - cron: 0 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - ID-text

ID-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update id"
  enabled: true
  environment: scrapers

ID-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update id events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 20 5 * * ?
  timeout_minutes: 60
