IL-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update il bills"
  enabled: true
  environment: scrapers
  memory: 1024
  triggers:
    - cron: 0 6 * * ?
  timeout_minutes: 900 # regularly 12 hours, 15 to be safe
  next_tasks:
    - IL-text

IL-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update il"
  enabled: true
  environment: scrapers
