IL-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update il bills"
  enabled: true
  environment: scrapers
  memory: 1024
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 6 * * ?
  timeout_minutes: 1080 # regularly 12 hours, 18 to be safe
  next_tasks:
    - IL-text

IL-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update il"
  enabled: true
  environment: scrapers

IL-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update il events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 25 5 * * ?
  timeout_minutes: 60
