IL-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update il bills --realtime"
  enabled: false
  environment: scrapers
  memory: 1024
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 10 6 * * ?
  timeout_minutes: 2160 # regularly 12 hours, 36 hours to be safe :(
  next_tasks:
    - IL-text

IL-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update il"
  enabled: false
  environment: scrapers

IL-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update il events"
  enabled: false
  environment: scrapers
  triggers:
    - cron: 25 */6 * * ?
  timeout_minutes: 60
