IN-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update in bills"
  enabled: false
  environment: scrapers
  triggers:
    - cron: 0 6 * * ?
  timeout_minutes: 360
  next_tasks:
    - IN-text

IN-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update in"
  enabled: true
  environment: scrapers
