IN-scrape:
  image: openstates/openstates
  entrypoint: "poetry run pupa update in bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 6 * * ?
  next_tasks:
    - IN-text

IN-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update in"
  enabled: true
  environment: scrapers
