IN-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update in bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */12 * * ?
#    - cron: 0 6 * * ?
  timeout_minutes: 720
  next_tasks:
    - IN-text

IN-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update in"
  enabled: true
  environment: scrapers
