KS-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ks bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - KS-text

KS-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update ks"
  enabled: true
  environment: scrapers
