LA-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update la bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */2 * * ?
#    - cron: 0 6 * * ?
  timeout_minutes: 360
  next_tasks:
    - LA-text

LA-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update la"
  enabled: true
  environment: scrapers
