MA-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update ma bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 5 * * ?
  timeout_minutes: 1440
  next_tasks:
    - MA-text

MA-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update ma"
  enabled: true
  environment: scrapers
