MA-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ma bills sort=latest page_limit=20"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 2160  # 36 hours :(
  next_tasks:
    - MA-text

MA-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update ma"
  enabled: true
  environment: scrapers
