ME-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update me bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 4 * * ?
  timeout_minutes: 360
  next_tasks:
    - ME-text

ME-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update me"
  enabled: true
  environment: scrapers
