ME-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update me bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 4 * * ?
  timeout_minutes: 360
  next_tasks:
    - ME-text

ME-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update me"
  enabled: true
  environment: scrapers
