MI-scrape:
  image: openstates/openstates
  entrypoint: "poetry run pupa update mi bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 6 * * ?
  next_tasks:
    - MI-text

MI-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update mi"
  enabled: true
  environment: scrapers
