MI-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update mi bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 6 * * ?
  timeout_minutes: 360
  memory: 1024
  next_tasks:
    - MI-text

MI-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update mi"
  enabled: true
  environment: scrapers
