MN-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update mn bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */2 * * ?
#    - cron: 0 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - MN-text

MN-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update mn"
  enabled: true
  environment: scrapers
