MO-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update mo bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 6 * * ?
  timeout_minutes: 360
  next_tasks:
    - MO-text

MO-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update mo"
  enabled: true
  environment: scrapers
