MO-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update mo bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 6 * * ?
  next_tasks:
    - MO-text

MO-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update mo"
  enabled: true
  environment: scrapers
