MT-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update mt bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - MT-text

MT-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update mt"
  enabled: true
  environment: scrapers
