MT-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update mt bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 7,22 * * ?
  timeout_minutes: 360
  next_tasks:
    - MT-text

MT-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update mt"
  enabled: true
  environment: scrapers

MT-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update mt events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 5 1 * * ?
  timeout_minutes: 60
