NC-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update nc bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 4 * * ?
  next_tasks:
    - NC-text

NC-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update nc"
  enabled: true
  environment: scrapers
