NC-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update nc bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */2 * * ?
#    - cron: 0 4 * * ?
  timeout_minutes: 360
  next_tasks:
    - NC-text

NC-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update nc"
  enabled: true
  environment: scrapers
