ND-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update nd bills" # votes
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 7 * * ?
  next_tasks:
    - ND-text

ND-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update nd"
  enabled: true
  environment: scrapers
