NE-scrape:
  image: openstates/openstates
  entrypoint: "poetry run pupa update ne bills" # votes
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 7 * * ?
  next_tasks:
    - NE-text

NE-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update ne"
  enabled: true
  environment: scrapers
