NE-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ne bills" # votes
  enabled: true
  environment: scrapers
  triggers:
    - cron: 20 */2 * * *
#    - cron: 0 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - NE-text

NE-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ne"
  enabled: true
  environment: scrapers

NE-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ne events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 9 * * *
  timeout_minutes: 60
