NE-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ne bills" # votes
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - NE-text

NE-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update ne"
  enabled: true
  environment: scrapers
