NH-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update nh bills"
  enabled: false
  environment: scrapers
  triggers:
    - cron: 0 5 * * ?
  timeout_minutes: 360
  next_tasks:
    - NH-text

NH-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update nh"
  enabled: true
  environment: scrapers
