NH-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update nh bills"
  enabled: true
  environment: scrapers
  triggers:
#    - cron: 0 4 * * ?
#   http://www.gencourt.state.nh.us/scrap/scrape.html
#   NH is limiting scraping to during the night only
#   2 a.m. - 11 a.m. UTC should be 9 p.m. - 6 a.m. EDT
    - cron: 0 2,4,6,8,10 * * ?
  timeout_minutes: 360
  next_tasks:
    - NH-text

NH-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update nh"
  enabled: true
  environment: scrapers

NH-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update nh events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 20 9 * * ?
  timeout_minutes: 60
