NJ-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update nj bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 4 * * ?
  timeout_minutes: 360
  next_tasks:
    - NJ-text

NJ-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update nj"
  enabled: true
  environment: scrapers
