NJ-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update nj bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 4 * * ?
  next_tasks:
    - NJ-text

NJ-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update nj"
  enabled: true
  environment: scrapers
