NM-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update nm bills"  # votes
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 7 * * ?
  next_tasks:
    - NM-text

NM-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update nm"
  enabled: true
  environment: scrapers
