NV-scrape:
  image: openstates/openstates
  entrypoint: "poetry run pupa update nv bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 8 * * ?
  next_tasks:
    - NV-text

NV-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update nv"
  enabled: true
  environment: scrapers
