NY-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update ny bills"
  enabled: true
  environment: scrapers
  memory: 1024
  triggers:
    - cron: 0 5 * * ?
  timeout_minutes: 360
  next_tasks:
    - NY-text

NY-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update ny"
  enabled: true
  environment: scrapers
