NY-scrape-2020:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ny bills session=2019-2020"
  enabled: false
  environment: scrapers
  memory: 1024
  timeout_minutes: 600  # regularly 7 hours, 10 to be safe
  next_tasks:
    - NY-text

NY-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ny bills"
  enabled: true
  environment: scrapers
  memory: 1024
  triggers:
    - cron: 0 5 * * ?
  timeout_minutes: 600  # regularly 7 hours, 10 to be safe
  next_tasks:
    - NY-text

NY-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update ny"
  enabled: true
  environment: scrapers
