OH-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update oh bills --realtime"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 40 */2 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 360
  next_tasks:
    - OH-text

OH-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update oh"
  enabled: true
  environment: scrapers

OH-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update oh events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 12 * * ?
  timeout_minutes: 60
