OH-scrape:
  image: openstates/openstates
  entrypoint: "poetry run pupa update oh bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 5 * * ?
  next_tasks:
    - OH-text

OH-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update oh"
  enabled: true
  environment: scrapers
