OK-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ok bills --realtime"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 25 */4 * * ?
#    - cron: 0 6 * * ?
  timeout_minutes: 360
  next_tasks:
    - OK-text

OK-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ok"
  enabled: true
  environment: scrapers

OK-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ok events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 10 12 * * ?
  timeout_minutes: 60
