OK-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ok bills"
  enabled: true
  environment: scrapers
  triggers:
#    - cron: 0 */6 * * ?
    - cron: 0 6 * * ?
  timeout_minutes: 360
  next_tasks:
    - OK-text

OK-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ok"
  enabled: true
  environment: scrapers
