OK-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ok bills --realtime"
  enabled: false
  environment: scrapers
  triggers:
    - cron: 25 */4 * * ?
#    - cron: 0 6 * * ?
  timeout_minutes: 720
  next_tasks:
    - OK-text

OK-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ok"
  enabled: false
  environment: scrapers

OK-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ok events"
  enabled: false
  environment: scrapers
  triggers:
    - cron: 10 */6 * * ?
  timeout_minutes: 60
