OR-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update or bills votes"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */2 * * ?
#    - cron: 0 8 * * ?
  timeout_minutes: 360
  next_tasks:
    - OR-text

OR-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update or"
  enabled: true
  environment: scrapers

OR-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update or events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 45 3 * * ?
  timeout_minutes: 60
