OR-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update or bills votes"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */2 * * ?
#    - cron: 0 8 * * ?
  timeout_minutes: 360
  next_tasks:
    - OR-text

OR-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update or"
  enabled: true
  environment: scrapers
