update-people:
  image: openstates/people:latest
  entrypoint: "poetry run ./scripts/to_database.py"
  enabled: true
  environment: backups
  triggers:
    - cron: 0 0 * * ?
people-csv:
  image: openstates/people:latest
  entrypoint: "poetry run ./scripts/to_csv.py --upload"
  enabled: true
  environment: backups
  triggers:
    - cron: 0 0 * * ?
backup:
  image: openstates/tasks
  entrypoint: "./backup"
  enabled: true
  environment: backups
  triggers:
    - cron: 0 0 * * ?
csv-export:
  image: openstates/openstates.org
  environment: scrapers
  enabled: true
  memory: 1024
  entrypoint: "poetry run ./manage.py bulk_export all --all --format csv"
  triggers:
    # first of the month
    - cron: 0 0 1 * ?
