update-people:
  image: openstates/people:latest
  entrypoint: "poetry run ./scripts/to_database.py"
  enabled: true
  environment: backups
  triggers:
    - cron: 0 0 * * ?
people-csv:
  image: openstates/people:latest
  entrypoint: "poetry run ./scripts/to_csv.py --upload"
  enabled: true
  environment: backups
  triggers:
    - cron: 0 0 * * ?
backup:
  image: openstates/tasks
  entrypoint: "./backup"
  enabled: true
  environment: backups
  triggers:
    - cron: 0 0 * * ?
csv-export:
  image: openstates/openstates.org
  environment: backups
  enabled: true
  entrypoint: "poetry run ./manage.py bulk_export ca --all --format csv"
