update-people:
  image: openstates/people:latest
  entrypoint: "poetry run ./scripts/to_database.py"
  enabled: true
  environment: commands
  triggers:
    - cron: 0 0 * * ?
people-csv:
  image: openstates/people:latest
  entrypoint: "poetry run ./scripts/to_csv.py --upload"
  enabled: true
  environment: commands
  triggers:
    - cron: 0 0 * * ?
backup:
  image: openstates/tasks
  entrypoint: "./backup"
  enabled: true
  environment: backups
  triggers:
    - cron: 0 0 * * ?
csv-export:
  image: openstates/openstates.org:django-dev
  environment: commands
  enabled: true
  memory: 4096
  cpu: 512
  entrypoint: "poetry run ./manage.py bulk_export all --format csv --all-sessions"
  triggers:
    # first of the month
    - cron: 0 0 1 * ?

web-update-bundles:
  image: openstates/openstates.org:django-dev
  environment: commands
  enabled: true
  entrypoint: ['poetry', 'run', './manage.py', 'manage_bundle', 'covid19', '--search', 'coronavirus OR covid', '--name', '"Coronavirus / COVID-19 Legislation"']
  triggers:
    - cron: 0 4 * * ?

data-quality-report:
  image: openstates/openstates.org:django-dev
  environment: commands
  enabled: false
  memory: 1024
  entrypoint: ['poetry', 'run', './manage.py', 'tx']
  triggers:
    - cron: 0 6 * * ?
