update-people:
  image: openstates/people:latest
  entrypoint: "poetry run ./scripts/to_database.py"
  enabled: true
  environment: backups
  triggers:
    - cron: 0 0 * * ?
backup:
  image: openstates/tasks
  entrypoint: "./backup"
  enabled: true
  environment: backups
  triggers:
    - cron: 0 0 * * ?
