backup:
  image: openstates/openstates.org:tasks
  entrypoint: "/code/docker/cron/backup.sh"
  enabled: true
  environment: backups
  triggers:
    - cron: 0 0 * * ?

csv-export:
  image: openstates/openstates.org:tasks
  environment: commands
  enabled: true
  memory: 4096
  cpu: 512
  entrypoint: "poetry run ./manage.py bulk_export all --format csv --with-updates 7"
  triggers:
    # every day
    - cron: 0 23 * * ?

json-export:
  image: openstates/openstates.org:tasks
  environment: commands
  enabled: true
  memory: 4096
  cpu: 512
  entrypoint: "poetry run ./manage.py bulk_export all --format json --with-updates 40"
  triggers:
    - cron: 0 23 1 * ?

web-update-bundles:
  image: openstates/openstates.org:tasks
  environment: commands
  enabled: true
  entrypoint: ['poetry', 'run', './manage.py', 'manage_bundle', 'covid19', '--search', 'coronavirus OR covid', '--name', '"Coronavirus / COVID-19 Legislation"']
  triggers:
    - cron: 0 4 * * ?

data-quality-report:
  image: openstates/openstates.org:tasks
  environment: commands
  enabled: true
  memory: 1024
  entrypoint: ['poetry', 'run', './manage.py', 'data_quality', 'all']
  triggers:
    - cron: 0 6 * * ?
