update-people:
  image: openstates/people
  entrypoint: "scripts/to_database.py"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 0 * * ?
backup:
  image: openstates/tasks
  entrypoint: "./backup"
  enabled: true
  environment: backups
  triggers:
    - cron: 0 0 * * ?
