PA-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update pa bills"
  enabled: true
  memory: 1024
  environment: scrapers
  triggers:
    - cron: 0 5 * * ?
  next_tasks:
    - PA-text

PA-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update pa"
  enabled: true
  environment: scrapers
