PA-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update pa bills --realtime"
  enabled: false
  memory: 1024
  environment: scrapers
  triggers:
    - cron: 0 */4 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 1080 # 18 hours to be safe :(
  next_tasks:
    - PA-text

PA-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update pa"
  enabled: false
  environment: scrapers

PA-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update pa events"
  enabled: false
  environment: scrapers
  triggers:
    - cron: 20 */6 * * ?
  timeout_minutes: 60
