PR-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update pr bills --realtime"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 4 * * ?
  timeout_minutes: 2160
  next_tasks:
    - PR-text

PR-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update pr"
  enabled: true
  environment: scrapers
