RI-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ri bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 35 */2 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 360
  next_tasks:
    - RI-text

RI-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ri"
  enabled: true
  environment: scrapers

RI-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ri events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 30 12 * * ?
  timeout_minutes: 60
