RI-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ri bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 360
  next_tasks:
    - RI-text

RI-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ri"
  enabled: true
  environment: scrapers
