SC-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update sc bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 4 * * ?
  timeout_minutes: 1200
  next_tasks:
    - SC-text

SC-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update sc"
  enabled: true
  environment: scrapers
