SC-scrape:
  image: openstates/openstates
  entrypoint: "poetry run pupa update sc bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 4 * * ?
  next_tasks:
    - SC-text

SC-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update sc"
  enabled: true
  environment: scrapers
