SC-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update sc bills --realtime"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */4 * * ?
#    - cron: 0 4 * * ?
  timeout_minutes: 1200
  next_tasks:
    - SC-text

SC-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update sc"
  enabled: true
  environment: scrapers

SC-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update sc events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 40 12 * * ?
  timeout_minutes: 60
