SD-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update sd bills"
  enabled: true
  environment: scrapers
  triggers:
#    - cron: 55 */3 * * ?
    - cron: 5 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - SD-text

SD-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update sd"
  enabled: true
  environment: scrapers

SD-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update sd events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 50 12 * * ?
  timeout_minutes: 60
