SD-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update sd bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#     - cron: 0 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - SD-text

SD-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update sd"
  enabled: true
  environment: scrapers
