TN-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update tn bills"
  enabled: true
  memory: 1024
  environment: scrapers
  triggers:
    - cron: 0 */2 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 360
  next_tasks:
    - TN-text

TN-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update tn"
  enabled: true
  environment: scrapers
