TX-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update tx bills votes"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 5 * * ?
  timeout_minutes: 360
  next_tasks:
    - TX-text

TX-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update tx"
  enabled: true
  environment: scrapers
