TX-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update tx bills votes"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 480
  next_tasks:
    - TX-text

TX-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update tx"
  enabled: true
  environment: scrapers
