UT-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update ut bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 8 * * ?
  next_tasks:
    - UT-text

UT-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update ut"
  enabled: true
  environment: scrapers
