VA-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update va bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 0 * * ?
  timeout_minutes: 360
  next_tasks:
    - VA-text

VA-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update va"
  enabled: true
  environment: scrapers
