VT-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update vt bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 480
  next_tasks:
    - VT-text

VT-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update vt"
  enabled: true
  environment: scrapers
