VT-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update vt bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 5 * * ?
  timeout_minutes: 480
  next_tasks:
    - VT-text

VT-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update vt"
  enabled: true
  environment: scrapers
