VT-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update vt bills --realtime"
  enabled: false
  environment: scrapers
  triggers:
    - cron: 27 */4 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 480
  next_tasks:
    - VT-text

VT-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update vt"
  enabled: false
  environment: scrapers

VT-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update vt events"
  enabled: false
  environment: scrapers
  triggers:
    - cron: 10 */6 * * ?
  timeout_minutes: 60
