WA-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update wa bills --realtime"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */6 * * ?
#    - cron: 0 8 * * ?
  timeout_minutes: 480
  next_tasks:
    - WA-text

WA-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update wa"
  enabled: true
  environment: scrapers

WA-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update wa events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 50 */6 * * ?
  timeout_minutes: 60
