WA-scrape:
  image: openstates/openstates
  entrypoint: "poetry run pupa update wa bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 8 * * ?
  next_tasks:
    - WA-text

WA-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update wa"
  enabled: true
  environment: scrapers
