WI-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update wi bills"
  enabled: true
  environment: scrapers
  triggers:
#    - cron: 0 */6 * * ?
    - cron: 0 6 * * ?
  timeout_minutes: 360
  next_tasks:
    - WI-text

WI-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update wi"
  enabled: true
  environment: scrapers
