WI-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update wi bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 6 * * ?
  next_tasks:
    - WI-text

WI-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update wi"
  enabled: true
  environment: scrapers
