WI-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update wi bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 53 */3 * * ?
#    - cron: 0 6 * * ?
  timeout_minutes: 360
  next_tasks:
    - WI-text

WI-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update wi"
  enabled: true
  environment: scrapers

WI-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update wi events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 20 13 * * ?
  timeout_minutes: 60
