WY-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update wy bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */2 * * ?
#    - cron: 0 8 * * ?
  timeout_minutes: 360
  next_tasks:
    - WY-text

WY-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update wy"
  enabled: true
  environment: scrapers

WY-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update wy events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 30 13 * * ?
  timeout_minutes: 60
