WY-scrape:
  image: openstates/openstates
  entrypoint: "poetry run os-update wy bills"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 8 * * ?
  timeout_minutes: 360
  next_tasks:
    - WY-text

WY-text:
  image: openstates/text-extraction
  entrypoint: "poetry run ./text_extract.py update wy"
  enabled: true
  environment: scrapers
