name: CI
on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Yaml file linting
        run: |
          docker run --rm \
          -v $(pwd):/code \
          registry.gitlab.com/pipeline-components/yamllint:latest \
          -c .yamllint.yml -s .
